"""Database schema definitions and creation entrypoint."""

from .schema_sql import (
    SCHEMA_INIT_LOCK_KEY,
    CREATE_USER_SETTINGS_TABLE,
    CREATE_USER_PERSONAS_TABLE,
    CREATE_PERSONAS_INDEX,
    CREATE_USER_SESSIONS_TABLE,
    CREATE_SESSIONS_INDEX,
    CREATE_USER_CONVERSATIONS_TABLE,
    CREATE_CONVERSATIONS_INDEX,
    CREATE_CONVERSATIONS_SESSION_INDEX,
    CREATE_USER_PERSONA_TOKENS_TABLE,
    CREATE_USER_MEMORIES_TABLE,
    CREATE_MEMORIES_INDEX,
    CREATE_USER_LOGS_TABLE,
    CREATE_USER_LOGS_INDEX,
    CREATE_USER_CRON_TASKS_TABLE,
    CREATE_CRON_TASKS_INDEX,
    CREATE_USER_SKILLS_TABLE,
    CREATE_USER_SKILLS_INDEX,
    CREATE_USER_SKILL_STATES_TABLE,
    CREATE_USER_SKILL_ARTIFACTS_TABLE,
    CREATE_WECHAT_RUNTIME_STATE_TABLE,
)

SCHEMA_STATEMENTS = [
    CREATE_USER_SETTINGS_TABLE,
    CREATE_USER_PERSONAS_TABLE,
    CREATE_PERSONAS_INDEX,
    CREATE_USER_SESSIONS_TABLE,
    CREATE_SESSIONS_INDEX,
    CREATE_USER_CONVERSATIONS_TABLE,
    CREATE_CONVERSATIONS_INDEX,
    CREATE_CONVERSATIONS_SESSION_INDEX,
    CREATE_USER_PERSONA_TOKENS_TABLE,
    CREATE_USER_MEMORIES_TABLE,
    CREATE_MEMORIES_INDEX,
    CREATE_USER_LOGS_TABLE,
    CREATE_USER_LOGS_INDEX,
    CREATE_USER_CRON_TASKS_TABLE,
    CREATE_CRON_TASKS_INDEX,
    CREATE_USER_SKILLS_TABLE,
    CREATE_USER_SKILLS_INDEX,
    CREATE_USER_SKILL_STATES_TABLE,
    CREATE_USER_SKILL_ARTIFACTS_TABLE,
    CREATE_WECHAT_RUNTIME_STATE_TABLE,
]


def create_tables(connection):
    """Create all required database tables."""
    with connection.cursor() as cur:
        cur.execute("SELECT pg_advisory_xact_lock(%s)", (SCHEMA_INIT_LOCK_KEY,))
        for statement in SCHEMA_STATEMENTS:
            cur.execute(statement)
    connection.commit()
