"""Voice and screenshot delivery for AI chat.

Handles delivering pending TTS voice messages and screenshots
that were generated by tool calls during the chat response.
"""

import io
import logging

from telegram import Update
from telegram.error import BadRequest

from tools import drain_pending_voice_jobs, drain_pending_screenshot_jobs

logger = logging.getLogger(__name__)


async def send_screenshot_with_fallback(
    update: Update,
    image_data: bytes,
    filename: str,
    caption: str | None,
) -> None:
    """Send screenshot as photo, fallback to document when Telegram rejects dimensions."""
    photo_file = io.BytesIO(image_data)
    photo_file.name = filename
    try:
        await update.message.reply_photo(photo=photo_file, caption=caption)
        return
    except BadRequest as e:
        message = str(e or "")
        if "invalid_dimensions" not in message.lower():
            raise
        logger.warning(
            "Telegram rejected photo dimensions; retrying screenshot as document (file=%s, bytes=%d)",
            filename,
            len(image_data),
        )

    # Retry as document to bypass photo dimension constraints.
    doc_file = io.BytesIO(image_data)
    doc_file.name = filename
    await update.message.reply_document(document=doc_file, caption=caption)


async def deliver_pending_voices(update: Update, user_id: int) -> None:
    """Deliver any pending TTS voice messages generated during the chat."""
    pending_voices = drain_pending_voice_jobs(user_id)
    for idx, job in enumerate(pending_voices, 1):
        audio_data = job.get("audio")
        if not audio_data:
            continue

        voice_file = io.BytesIO(audio_data)
        voice_file.name = job.get("filename", f"tts_{idx}.ogg")

        try:
            await update.message.reply_voice(
                voice=voice_file,
                caption=job.get("caption"),
            )
        except Exception:
            logger.exception("Failed to send pending tts voice")


async def deliver_pending_screenshots(update: Update, user_id: int) -> None:
    """Deliver any pending screenshots generated during the chat."""
    pending_screenshots = drain_pending_screenshot_jobs(user_id)
    for idx, job in enumerate(pending_screenshots, 1):
        image_data = job.get("image")
        if not image_data:
            continue
        filename = job.get("filename", f"screenshot_{idx}.png")
        try:
            await send_screenshot_with_fallback(
                update,
                image_data=image_data,
                filename=filename,
                caption=job.get("caption"),
            )
        except Exception:
            logger.exception("Failed to send pending screenshot")
