"""Schema constants split by domain."""

from .user_data import (
    SCHEMA_INIT_LOCK_KEY,
    CREATE_USER_SETTINGS_TABLE,
    CREATE_USER_PERSONAS_TABLE,
    CREATE_PERSONAS_INDEX,
    CREATE_USER_SESSIONS_TABLE,
    CREATE_SESSIONS_INDEX,
    CREATE_USER_CONVERSATIONS_TABLE,
    CREATE_CONVERSATIONS_INDEX,
    CREATE_CONVERSATIONS_SESSION_INDEX,
)
from .tokens_settings_migrations import (
    CREATE_USER_PERSONA_TOKENS_TABLE,
    MIGRATE_PERSONA_TOKENS_ADD_LIMIT,
    MIGRATE_SETTINGS_ADD_CRON_MODEL,
    MIGRATE_SETTINGS_ADD_STREAM_MODE,
    MIGRATE_SETTINGS_ADD_GLOBAL_PROMPT,
    MIGRATE_SETTINGS_ADD_REASONING_EFFORT,
    MIGRATE_SETTINGS_ADD_SHOW_THINKING,
)
from .memory_logs_cron import (
    CREATE_USER_MEMORIES_TABLE,
    CREATE_MEMORIES_INDEX,
    CREATE_USER_LOGS_TABLE,
    CREATE_USER_LOGS_INDEX,
    CREATE_USER_CRON_TASKS_TABLE,
    CREATE_CRON_TASKS_INDEX,
)
from .skills_wechat import (
    CREATE_USER_SKILLS_TABLE,
    CREATE_USER_SKILLS_INDEX,
    CREATE_USER_SKILL_STATES_TABLE,
    CREATE_USER_SKILL_ARTIFACTS_TABLE,
    CREATE_WECHAT_RUNTIME_STATE_TABLE,
)
